### PR TITLE
Add RoboSherlockAccountAuthenticatorFragmentActivity

### PR DESCRIPTION
**Pull request by jondwillis**
Primarily this allows us to use getSupportFragmentManager() to support using fragments in subclasses.

This could/should be done for all RoboSherlock*Activities, but alas I am lazy.

### CODE REVIEW

**Comment by JakeWharton** [comment]
I don't see the value here in including these in this library. Why not extend from `RoboSherlockFragmentActivity` with the authenticator stuff and be done with it?

**Comment by jondwillis** [comment]
I suppose my reasoning was that it keeps the duplicate code all in one place, so clients of roboguice-sherlock don't need to worry about updating their own copy of RoboSherlockAccountAuthenticatorFragmentActivity. 

I agree that it is kind of out of the scope of this library though :\

**Comment by JakeWharton** [comment]
Yeah it is unfortunate that all this functionality requires base activities. Probably my least favorite thing about ABS (though it supports attaching without a base activity but it's less elegant).

**Comment by jondwillis** [comment]
Indeed. By the way, do you have write-access to this repo? It must be pretty exhausting to keep up with all of this since ABS is kind of the keystone of modern android development. While I have you here, I gotta dap you up for all of these great libraries. I've been using Otto in my most recent project and using it is just a dream. Cheers!

**Comment by rtyley** [comment]
@JakeWharton is welcome to commit access on roboguice-sherlock if he wants it- pull requests work pretty well most of the time though. I'm afraid I agree with him about this PR being out of scope, thanks for closing.

In any case, I'm glad roboguice-sherlock is of use to you!

**Pull request closed without merging**
