### PR TITLE
Two Fixes. Er, One Fix now...

### PR DESCRIPTION
**Pull request by JakeWharton**
1. <del>Add my release repository as a remote since someone without it already in their local repo will get a failure when it searches central.</del>
2. Use the GitHub downloads plugin to upload the `.jar` artifact to the project when releasing a new version. I tested this as best I could. You'll need to following in your `~/.m2/settings.xml` if you don't already have it:
   
   ``` xml
   <profiles>
       <profile>
           <id>github</id>
           <properties>
               <github.global.userName>rtyley</github.global.userName>
               <github.global.password>rainbow sprinkles!!!!</github.global.password>
           </properties>
       </profile>
   </profiles>
   <activeProfiles>
       <activeProfile>github</activeProfile>
   </activeProfiles>
   ```
   
   Replace with your real password. Assuming I didn't just guess it exactly...

### CODE REVIEW

**Comment by rtyley** [comment]
@JakeWharton, I notice you had [OSSRH-3000](https://issues.sonatype.org/browse/OSSRH-3000) approved, so you should be able to stage artifacts in oss.sonatype.org - once you've done that, let Juven Xu know and he'll start them syncing with Maven Central. Wouldn't that be best in terms of convenience for ABS users?

Incidentally, I'm not certain how strong the ban on artifacts with non-Maven Central dependencies is - according to http://maven.apache.org/guides/mini/guide-central-repository-upload.html#FAQ_and_common_mistakes :

> _I have other repositories or pluginRepositories listed in my POM, is that a problem?_
> 
> At present, this **won't preclude your project from being included**, but we do strongly encourage making sure all your dependencies are included in Central. If you rely on sketchy repositories that have junk in them or disappear, it just creates havok for downstream users. Try to keep your dependencies among reliable repos like Central, Jboss, etc.

Obviously, even that's not an issue with ABS anymore, as it no longer has any non-MC dependencies. **Get that wonderful library into Maven Central man!** :metal:

**Comment by JakeWharton** [comment]
Seeking that approval was dependent on library projects being able to be contained in `.jar`s which was supposed to come with ADT17 but now looks to yet again be delayed. As far as I remember when I set up the `com.jakewharton` repo a while ago they didn't allow non-jar artifacts to be uploaded so I wouldn't be able to fully publish the necessary `.apklib` containing the resources. I could publish just the `.jar` for linking against but I'm worried that it would cause confusion. I'll have to investigate further.

And I totally forgot about the linking to non-central repositories requirement. It's a bit late here so I'll blame exhaustion for that one.

I'll revert/rebase/push -f quickly so that it's only the downloads plugin for now.

**Comment by rtyley** [comment]
Ah, that's interesting - I hope you're wrong about the _non-jar-artifact_ rule, I know that there are already a [few apklib artifacts](http://search.maven.org/#search%7Cga%7C1%7Cp%3A%22apklib%22) in Central, which would indicate at least that it isn't strictly enforced.

If possible, please send me a link/reference to that requirement (couldn't see it on the [maven](http://maven.apache.org/guides/mini/guide-central-repository-upload.html) or [sonatype](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-6.CentralSyncRequirement) pages), as I'd like to have a chat with them about relaxing it.

In any case, thanks for the pull request - merging now :sparkles:

**Comment by JakeWharton** [comment]
```
[INFO] Executing: /bin/sh -c cd /home/roberto/development/roboguice-sherlock/target/checkout && /home/roberto/tools/maven/current/bin/mvn deploy --no-plugin-updates -Psonatype-oss-release -P compiler,default -f pom.xml
```

I guess you could latch on to the `sonatype-oss-release` profile but then you're at the mercy of whatever that plugin chooses to use in the future.

I find it odd that it didn't fire as I used a similar setup previously when I had my own GitHub maven deployer.

You could just latch onto the `deploy` phase with no profile if you don't ever plan to deploy snapshots but I don't think that's the correct solution.

**Pull request merged**
