### PR TITLE
Fix incompatibility with RoboGuice 2.0

### PR DESCRIPTION
**Pull request by rfc1459**
Due to stricter requirements in RoboGuice 2.0, all Activity subclasses must implement RoboContext.

This commit also adds a series of tests for `RoboSherlockActivity` modeled after the ones for `RoboActivity` in RoboGuice.

### CODE REVIEW

**Comment by rtyley** [comment]
Hi @rfc1459, thanks for doing this, its really great to see this as I wasn't aware of the recent changes in RoboGuice 2.0-RC2!

Unfortunately the commit seems to be larger than it needs to be because it includes a lot of extra `import` changes (sometimes even touching files where no other changes have occurred) - could you trim the commit to be smaller by excluding those superfluous extra changes?

**Comment by rfc1459** [comment]
Sure, although I'm not sure what strategy I should use to amend this (a new pull request with a clean commit?)
Sorry for the mess, by the way, I found out the problem only after I submitted the request.

**Comment by JakeWharton** [comment]
Since it's only one commit amending is usually the easiest way.
1. Make your changes.
2. `git commit -a -C HEAD --amend` _(this is a trick to commit all files, amend it to previous, and skip changing the commit message)_
3. `git push origin roboguice2-rc2 -f` _(force push the new history)_

This pull will automatically update itself once you push.

**Comment by rfc1459** [comment]
@JakeWharton Thanks for the tip, I didn't know that the pull request would update itself after a forced push.

Anyway, I fixed the imports and resubmitted the commit. The warnings emitted by Robolectric during test phase are harmless, since they're related to shadow classes for the Google Maps API.

**Comment by achuinard** [comment]
Was having this problem myself today - the fix was easy (having the activities implement RoboContext and store a scopedObjectsMap field).  It seems this commit did exactly that.  Hope it's integrated soon!

**Comment by JakeWharton** [comment]
2.0 final was just released so I'd hold off on merging until this can be updated to reflect.

**Comment by rfc1459** [comment]
Test results with RoboGuice 2.0 final:
`Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.551 sec`

Commit updated accordingly, the only residual reference to RC2 is in the topic branch name :-)

**Comment by rtyley** [comment]
Thanks to you @rfc1459 - much appreciated.

**Comment by rtyley** [comment]
This has been pushed to Maven Central with [v1.3](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.rtyley%22%20AND%20a%3A%22roboguice-sherlock%22) - should show up there in a few hours.

**Pull request merged**
