### PR TITLE
Change to the right exclusions of Roboguice

### PR DESCRIPTION
**Pull request by zhen9ao**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Actually you shouldn't need the exclusion at all. Maven will automatically use the newer r7 dependency specified by ABS.

**Comment by zhen9ao** [comment]
Maybe, just remove the exclusions?

**Comment by JakeWharton** [comment]
Yeah that should work as expected.

**Comment by zhen9ao** [comment]
How to test this project? I run `mvn clean test`, it fails.

**Comment by rfc1459** [comment]
`mvn clean test` does not fail:
`Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.541 sec`

The warnings emitted by Robolectric are harmless, they're due to the fact that maps.jar is not on the classpath, so it fails to shadow some maps-related classes. ~~I just failed to silence them properly~~ There is no way to silence those messages, just ignore them.

**Comment by zhen9ao** [comment]
While I run `mvn clean test`, I got the following:

> ---
> 
> Running com.github.rtyley.android.sherlock.roboguice.activity.SherlockActivityInjectionTest
> Warning: an error occurred while binding shadow class: ShadowGeoPoint
> Warning: an error occurred while binding shadow class: ShadowItemizedOverlay
> Warning: an error occurred while binding shadow class: ShadowMapController
> Warning: an error occurred while binding shadow class: ShadowMapActivity
> Warning: an error occurred while binding shadow class: ShadowMapView
> Warning: an error occurred while binding shadow class: ShadowOverlayItem
> Tests run: 13, Failures: 0, Errors: 13, Skipped: 0, Time elapsed: 1.642 sec <<< FAILURE!

With the `-X` param added, found some exceptions, such as:

> java.lang.RuntimeException: no such directory /Users/zheng/Documents/Android/android-sdk-mac_x86/platforms/android-3/data/res/values

Does that mean the project is depend on `android-3`?

**Comment by rfc1459** [comment]
OUCH, that was a mistake on my part. Sending a pull request ASAP.

**Comment by rtyley** [comment]
I've rebased this pull-request, merged it in to master, and also updated to ABS 4.0.2 to ensure we get r7 of the support-lib.

**Pull request closed without merging**
